version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: ilhas_calor_postgres
    restart: always
    environment:
      POSTGRES_USER: ilhas_user
      POSTGRES_PASSWORD: ilhas_pass
      POSTGRES_DB: ilhas_de_calor
    ports:
      - "5432:5432"
    volumes:
      - pgdata_ilhas:/var/lib/postgresql/data

volumes:
  pgdata_ilhas:
